apiVersion: apps/v1
kind: Deployment
metadata:
  name: insight-frontend-deployment
  labels:
    app: insight-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: insight-frontend
  template:
    metadata:
      labels:
        app: insight-frontend
    spec:
      containers:
        - name: insight-frontend
          imagePullPolicy: Always  
          image: flooth/insight-frontend:latest
          ports:
            - containerPort: 3000

---

apiVersion: v1
kind: Service
metadata:
  name: insight-frontend-service
  labels:
    run: insight-frontend
spec:
  type: ClusterIP
  ports:
  - port: 3000
    protocol: TCP
  selector:
    app: insight-frontend
