apiVersion: apps/v1
kind: Deployment
metadata:
  name: insight-deployment
  labels:
    app: insight
spec:
  replicas: 2
  selector:
    matchLabels:
      app: insight
  template:
    metadata:
      labels:
        app: insight
    spec:
      containers:
        - name: insight
          imagePullPolicy: Always  
          image: flooth/insight:latest
          ports:
            - containerPort: 3000

---

apiVersion: v1
kind: Service
metadata:
  name: insight-service
  labels:
    run: insight
spec:
  type: ClusterIP
  ports:
  - port: 3000
    protocol: TCP
  selector:
    app: insight
