apiVersion: apps/v1
kind: Deployment
metadata:
  name: personal-website-frontend-deployment
  labels:
    app: personal-website-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: personal-website-frontend
  template:
    metadata:
      labels:
        app: personal-website-frontend
    spec:
      containers:
        - name: personal-website-frontend
          imagePullPolicy: Always  
          image: flooth/personal-website-frontend:latest
          ports:
            - containerPort: 3000

---

apiVersion: v1
kind: Service
metadata:
  name: personal-website-frontend-service
  labels:
    run: personal-website-frontend
spec:
  type: ClusterIP
  ports:
  - port: 3000
    protocol: TCP
  selector:
    app: personal-website-frontend
