/* tslint:disable */
/* eslint-disable */
/**
 * PersonalWebsiteBackend
 * PersonalWebsiteBackend API Swagger Surface
 *
 * The version of the OpenAPI document: v1
 * Contact: thom.florian@yahoo.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    Document,
    DocumentFromJSON,
    DocumentFromJSONTyped,
    DocumentToJSON,
} from './';

/**
 * 
 * @export
 * @interface PagedResponseDocument
 */
export interface PagedResponseDocument {
    /**
     * 
     * @type {Array<Document>}
     * @memberof PagedResponseDocument
     */
    data?: Array<Document> | null;
    /**
     * 
     * @type {number}
     * @memberof PagedResponseDocument
     */
    pageNumber?: number | null;
    /**
     * 
     * @type {number}
     * @memberof PagedResponseDocument
     */
    pageSize?: number | null;
    /**
     * 
     * @type {string}
     * @memberof PagedResponseDocument
     */
    nextPage?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PagedResponseDocument
     */
    previousPage?: string | null;
    /**
     * 
     * @type {number}
     * @memberof PagedResponseDocument
     */
    pagesTotal?: number;
    /**
     * 
     * @type {number}
     * @memberof PagedResponseDocument
     */
    itemsTotal?: number;
}

export function PagedResponseDocumentFromJSON(json: any): PagedResponseDocument {
    return PagedResponseDocumentFromJSONTyped(json, false);
}

export function PagedResponseDocumentFromJSONTyped(json: any, ignoreDiscriminator: boolean): PagedResponseDocument {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'data': !exists(json, 'data') ? undefined : (json['data'] === null ? null : (json['data'] as Array<any>).map(DocumentFromJSON)),
        'pageNumber': !exists(json, 'pageNumber') ? undefined : json['pageNumber'],
        'pageSize': !exists(json, 'pageSize') ? undefined : json['pageSize'],
        'nextPage': !exists(json, 'nextPage') ? undefined : json['nextPage'],
        'previousPage': !exists(json, 'previousPage') ? undefined : json['previousPage'],
        'pagesTotal': !exists(json, 'pagesTotal') ? undefined : json['pagesTotal'],
        'itemsTotal': !exists(json, 'itemsTotal') ? undefined : json['itemsTotal'],
    };
}

export function PagedResponseDocumentToJSON(value?: PagedResponseDocument | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'data': value.data === undefined ? undefined : (value.data === null ? null : (value.data as Array<any>).map(DocumentToJSON)),
        'pageNumber': value.pageNumber,
        'pageSize': value.pageSize,
        'nextPage': value.nextPage,
        'previousPage': value.previousPage,
        'pagesTotal': value.pagesTotal,
        'itemsTotal': value.itemsTotal,
    };
}


