/* tslint:disable */
/* eslint-disable */
/**
 * PersonalWebsiteBackend
 * PersonalWebsiteBackend API Swagger Surface
 *
 * The version of the OpenAPI document: v1
 * Contact: thom.florian@yahoo.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface Document
 */
export interface Document {
    /**
     *
     * @type {string}
     * @memberof Document
     */
    id?: string;
    /**
     *
     * @type {string}
     * @memberof Document
     */
    documentId?: string | null;
    /**
     *
     * @type {string}
     * @memberof Document
     */
    name?: string | null;
    /**
     *
     * @type {string}
     * @memberof Document
     */
    description?: string | null;
    /**
     *
     * @type {string}
     * @memberof Document
     */
    ownersEmail?: string | null;
    /**
     *
     * @type {string}
     * @memberof Document
     */
    thumbnailLink?: string | null;
    /**
     *
     * @type {string}
     * @memberof Document
     */
    webcontentLink?: string | null;
    /**
     *
     * @type {string}
     * @memberof Document
     */
    webviewLink?: string | null;
    /**
     *
     * @type {string}
     * @memberof Document
     */
    fileExtension?: string | null;
    /**
     *
     * @type {string}
     * @memberof Document
     */
    fullFileExtension?: string | null;
    /**
     *
     * @type {string}
     * @memberof Document
     */
    kind?: string | null;
    /**
     *
     * @type {string}
     * @memberof Document
     */
    md5Checksum?: string | null;
    /**
     *
     * @type {boolean}
     * @memberof Document
     */
    shared?: boolean;
    /**
     *
     * @type {number}
     * @memberof Document
     */
    size?: number;
    /**
     *
     * @type {number}
     * @memberof Document
     */
    version?: number;
    /**
     *
     * @type {string}
     * @memberof Document
     */
    documentCreatedTime?: string | null;
    /**
     *
     * @type {string}
     * @memberof Document
     */
    userId?: string | null;
    /**
     *
     * @type {Date}
     * @memberof Document
     */
    createdOn?: Date;
    /**
     *
     * @type {string}
     * @memberof Document
     */
    creatorId?: string | null;
    /**
     *
     * @type {Date}
     * @memberof Document
     */
    updatedOn?: Date;
    /**
     *
     * @type {string}
     * @memberof Document
     */
    updaterId?: string | null;
}
