/* tslint:disable */
/* eslint-disable */
/**
 * PersonalWebsiteBackend
 * PersonalWebsiteBackend API Swagger Surface
 *
 * The version of the OpenAPI document: v1
 * Contact: thom.florian@yahoo.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    Project,
    ProjectFromJSON,
    ProjectFromJSONTyped,
    ProjectToJSON,
} from './';

/**
 * 
 * @export
 * @interface PagedResponseProject
 */
export interface PagedResponseProject {
    /**
     * 
     * @type {Array<Project>}
     * @memberof PagedResponseProject
     */
    data?: Array<Project> | null;
    /**
     * 
     * @type {number}
     * @memberof PagedResponseProject
     */
    pageNumber?: number | null;
    /**
     * 
     * @type {number}
     * @memberof PagedResponseProject
     */
    pageSize?: number | null;
    /**
     * 
     * @type {string}
     * @memberof PagedResponseProject
     */
    nextPage?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PagedResponseProject
     */
    previousPage?: string | null;
}

export function PagedResponseProjectFromJSON(json: any): PagedResponseProject {
    return PagedResponseProjectFromJSONTyped(json, false);
}

export function PagedResponseProjectFromJSONTyped(json: any, ignoreDiscriminator: boolean): PagedResponseProject {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'data': !exists(json, 'data') ? undefined : (json['data'] === null ? null : (json['data'] as Array<any>).map(ProjectFromJSON)),
        'pageNumber': !exists(json, 'pageNumber') ? undefined : json['pageNumber'],
        'pageSize': !exists(json, 'pageSize') ? undefined : json['pageSize'],
        'nextPage': !exists(json, 'nextPage') ? undefined : json['nextPage'],
        'previousPage': !exists(json, 'previousPage') ? undefined : json['previousPage'],
    };
}

export function PagedResponseProjectToJSON(value?: PagedResponseProject | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'data': value.data === undefined ? undefined : (value.data === null ? null : (value.data as Array<any>).map(ProjectToJSON)),
        'pageNumber': value.pageNumber,
        'pageSize': value.pageSize,
        'nextPage': value.nextPage,
        'previousPage': value.previousPage,
    };
}


