/* tslint:disable */
/* eslint-disable */
/**
 * PersonalWebsiteBackend
 * PersonalWebsiteBackend API Swagger Surface
 *
 * The version of the OpenAPI document: v1
 * Contact: thom.florian@yahoo.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface Project
 */
export interface Project {
    /**
     *
     * @type {string}
     * @memberof Project
     */
    id?: string;
    /**
     *
     * @type {string}
     * @memberof Project
     */
    name?: string | null;
    /**
     *
     * @type {boolean}
     * @memberof Project
     */
    archived?: boolean;
    /**
     *
     * @type {string}
     * @memberof Project
     */
    projectCreatedOn?: string | null;
    /**
     *
     * @type {string}
     * @memberof Project
     */
    description?: string | null;
    /**
     *
     * @type {number}
     * @memberof Project
     */
    forksCount?: number;
    /**
     *
     * @type {string}
     * @memberof Project
     */
    htmLUrl?: string | null;
    /**
     *
     * @type {number}
     * @memberof Project
     */
    projectId?: number;
    /**
     *
     * @type {string}
     * @memberof Project
     */
    language?: string | null;
    /**
     *
     * @type {string}
     * @memberof Project
     */
    licence?: string | null;
    /**
     *
     * @type {string}
     * @memberof Project
     */
    ownerName?: string | null;
    /**
     *
     * @type {string}
     * @memberof Project
     */
    ownerHtmlUrl?: string | null;
    /**
     *
     * @type {boolean}
     * @memberof Project
     */
    _private?: boolean;
    /**
     *
     * @type {number}
     * @memberof Project
     */
    size?: number;
    /**
     *
     * @type {number}
     * @memberof Project
     */
    stars?: number;
    /**
     *
     * @type {number}
     * @memberof Project
     */
    watchersCount?: number;
    /**
     *
     * @type {string}
     * @memberof Project
     */
    projectUpdatedOn?: string | null;
    /**
     *
     * @type {string}
     * @memberof Project
     */
    visibility?: string | null;
    /**
     *
     * @type {string}
     * @memberof Project
     */
    userId?: string | null;
    /**
     *
     * @type {string}
     * @memberof Project
     */
    createdOn?: string | null;
    /**
     *
     * @type {string}
     * @memberof Project
     */
    creatorId?: string | null;
    /**
     *
     * @type {string}
     * @memberof Project
     */
    updatedOn?: string | null;
    /**
     *
     * @type {string}
     * @memberof Project
     */
    updaterId?: string | null;
}
