/* tslint:disable */
/* eslint-disable */
/**
 * PersonalWebsiteBackend
 * PersonalWebsiteBackend API Swagger Surface
 *
 * The version of the OpenAPI document: v1
 * Contact: thom.florian@yahoo.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Project } from "@/src/openapi_models/models/Project";

/**
 *
 * @export
 * @interface ResponseProject
 */
export interface ResponseProject {
    /**
     *
     * @type {Project}
     * @memberof ResponseProject
     */
    data?: Project;
}
