/* tslint:disable */
/* eslint-disable */
/**
 * PersonalWebsiteBackend
 * PersonalWebsiteBackend API Swagger Surface
 *
 * The version of the OpenAPI document: v1
 * Contact: thom.florian@yahoo.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface UserLoginRequest
 */
export interface UserLoginRequest {
    /**
     *
     * @type {string}
     * @memberof UserLoginRequest
     */
    email?: string | null;
    /**
     *
     * @type {string}
     * @memberof UserLoginRequest
     */
    password?: string | null;
}
